[imap]
server = "imap.my-server.com"
port = 993
username = "my-username"
keyring_secret_name = "security_notifier_imap"
unseen_only = false

[cctv_alerts]
email_sender = "myname@mydevice.url"
email_subject_filter = "Embedded Net DVR"